server.port=8083

spring.application.name=pacienteService
spring.datasource.url=jdbc:postgresql://localhost:5432/pacientedb
spring.datasource.username=mediqueue
spring.datasource.password=mediqueue123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true

logging.level.root=INFO
logging.level.com.mediqueue.paciente=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
