server:
  port: 8081

spring:
  application:
    name: cita-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5000/mediqueueadmin}
    username: ${SPRING_DATASOURCE_USERNAME:mediqueue}
    password: ${SPRING_DATASOURCE_PASSWORD:mediqueue123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      sentinel:
        master: ${SPRING_DATA_REDIS_SENTINEL_MASTER:mymaster}
        nodes: ${SPRING_DATA_REDIS_SENTINEL_NODES:100.76.170.62:26379,100.115.210.113:26379,100.99.158.11:26379}
      timeout: 2s
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:100.76.170.62,100.115.210.113,100.99.158.11}
    username: ${SPRING_RABBITMQ_USERNAME:mediqueue}
    password: ${SPRING_RABBITMQ_PASSWORD:mediqueue123}
    connection-timeout: 5s
    publisher-confirm-type: ${SPRING_RABBITMQ_PUBLISHER_CONFIRM_TYPE:correlated}
    publisher-returns: ${SPRING_RABBITMQ_PUBLISHER_RETURNS:true}
    template:
      mandatory: true
  cache:
    type: redis

resilience4j:
  circuitbreaker:
    instances:
      dbCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      externalServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
  retry:
    instances:
      dbRetry:
        maxAttempts: 3
        waitDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    redis:
      enabled: true
    rabbit:
      enabled: true
    db:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

app:
  services:
    patient-url: ${PATIENT_SERVICE_URL:http://paciente-service:8083}
    doctor-url: ${DOCTOR_SERVICE_URL:http://doctor-horario:8082}
  rabbitmq:
    exchange: mediqueue.appointments.exchange
    appointment-created-queue: mediqueue.appointments.created
    appointment-cancelled-queue: mediqueue.appointments.cancelled
    appointment-created-routing-key: appointments.created
    appointment-cancelled-routing-key: appointments.cancelled
    rpc-exchange: mediqueue.rpc.exchange
    patient-validation-routing-key: paciente.validate
    doctor-validation-routing-key: doctor.validate

logging:
  level:
    com.mediqueue.cita_service: INFO
    org.hibernate.SQL: WARN
