cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@100.76.170.62
cluster_formation.classic_config.nodes.2 = rabbit@100.115.210.113
cluster_formation.classic_config.nodes.3 = rabbit@100.99.158.11
cluster_partition_handling = pause_minority
queue_master_locator = min-masters
loopback_users.guest = false
