server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: paciente-service
              uri: http://paciente-service:8083
              predicates:
                - Path=/api/pacientes/**

            - id: cita-service
              uri: http://cita-service:8081
              predicates:
                - Path=/api/v1/appointments/**

            - id: doctor-horario
              uri: http://doctor-horario:8082
              predicates:
                - Path=/api/horarios/**

            - id: pago-service
              uri: http://pago-service:8084
              predicates:
                - Path=/api/payments/**

            - id: pago-service-legacy
              uri: http://pago-service:8084
              predicates:
                - Path=/payments/**

            - id: notificacion-service
              uri: http://notificacion-service:8085
              predicates:
                - Path=/api/notificaciones/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
