server:
  port: 8080

spring:
  application:
    name: api-gateway

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:100.76.170.62:5672,100.113.35.88:5672,100.99.158.111:5672}
    username: ${SPRING_RABBITMQ_USERNAME:mediqueue}
    password: ${SPRING_RABBITMQ_PASSWORD:mediqueue123}

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
      server:
        webmvc:
          routes:

            - id: paciente-service
              uri: ${PACIENTE_SERVICE_URL:http://100.76.170.62:8083}
              predicates:
                - Path=/api/pacientes,/api/pacientes/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: pacienteCB
                    fallbackUri: forward:/fallback/paciente

            - id: cita-service
              uri: ${CITA_SERVICE_URL:http://100.113.35.88:8081}
              predicates:
                - Path=/api/v1/appointments,/api/v1/appointments/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: citaCB
                    fallbackUri: forward:/fallback/cita

            - id: doctor-horario
              uri: ${DOCTOR_SERVICE_URL:http://100.113.35.88:8082}
              predicates:
                - Path=/api/horarios,/api/horarios/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: doctorCB
                    fallbackUri: forward:/fallback/doctor

            - id: pago-service
              uri: ${PAGO_SERVICE_URL:http://100.99.158.111:8084}
              predicates:
                - Path=/api/payments,/api/payments/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: pagoCB
                    fallbackUri: forward:/fallback/pago

            - id: notificacion-service
              uri: ${NOTIFICACION_SERVICE_URL:http://100.99.158.111:8085}
              predicates:
                - Path=/api/notificaciones,/api/notificaciones/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: notificacionCB
                    fallbackUri: forward:/fallback/notificacion

resilience4j:
  circuitbreaker:
    instances:
      pacienteCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      citaCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
      doctorCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
      pagoCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
      notificacionCB:
        slidingWindowSize: 10
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

