server:
  port: 8080

spring:
  application:
    name: apiGateway

  cloud:
    gateway:
      routes:

        - id: paciente-service
          uri: http://pacienteService:8081
          predicates:
            - Path=/pacientes/**

        - id: cita-service
          uri: http://citaService:8083
          predicates:
            - Path=/citas/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus