spring.application.name=doctorHorarioService
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/doctordb
spring.datasource.username=mediqueue
spring.datasource.password=mediqueue123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true

logging.level.root=INFO
logging.level.com.mediqueue.doctorhorario=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
