global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: api_gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['100.76.170.62:8080']

  - job_name: paciente_service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['100.76.170.62:8083']

  - job_name: cita_service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['100.115.210.113:8081']

  - job_name: doctor_horario
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['100.115.210.113:8082']

  - job_name: pago_service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['100.99.158.111:8084']

  - job_name: notificacion_service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['100.99.158.111:8085']
