server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/pagodb
spring.datasource.username=mediqueue
spring.datasource.password=mediqueue123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:mediqueue}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:mediqueue123}

app.rabbitmq.payments-exchange=mediqueue.payments.exchange
app.rabbitmq.payment-success-queue=mediqueue.payments.success
app.rabbitmq.payment-failed-queue=mediqueue.payments.failed
app.rabbitmq.payment-success-routing-key=payments.success
app.rabbitmq.payment-failed-routing-key=payments.failed

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true

logging.level.payment_service=INFO
