server.port=8084

spring.application.name=pago-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5000/mediqueueadmin}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mediqueue}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mediqueue123}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES:100.76.170.62:5672,100.115.210.113:5672,100.99.158.11:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:mediqueue}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:mediqueue123}
spring.rabbitmq.publisher-confirm-type=${SPRING_RABBITMQ_PUBLISHER_CONFIRM_TYPE:correlated}
spring.rabbitmq.publisher-returns=${SPRING_RABBITMQ_PUBLISHER_RETURNS:true}
spring.rabbitmq.template.mandatory=true

# Resilience4j
resilience4j.circuitbreaker.instances.paymentDB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentDB.sliding-window-size=10
resilience4j.retry.instances.dbRetry.max-attempts=3
resilience4j.retry.instances.dbRetry.wait-duration=1s

app.rabbitmq.payments-exchange=mediqueue.payments.exchange
app.rabbitmq.payment-success-queue=mediqueue.payments.success
app.rabbitmq.payment-failed-queue=mediqueue.payments.failed
app.rabbitmq.payment-success-routing-key=payments.success
app.rabbitmq.payment-failed-routing-key=payments.failed
app.services.appointment-url=${APP_APPOINTMENT_SERVICE_URL:http://localhost:8081}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}

logging.level.payment_service=INFO
