server.port=8084 
//puertoarreglo

spring.datasource.url=jdbc:postgresql://localhost:5432/pagodb
spring.datasource.username=mediqueue
spring.datasource.password=mediqueue123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect