server:
  port: 8085

spring:
  application:
    name: notificacion-service
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:100.76.170.62:5672,100.113.35.88:5672,100.99.158.111:5672}
    username: ${SPRING_RABBITMQ_USERNAME:mediqueue}
    password: ${SPRING_RABBITMQ_PASSWORD:mediqueue123}
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          multiplier: 2
          max-interval: 10s

resilience4j:
  circuitbreaker:
    instances:
      notifCB:
        slidingWindowSize: 10
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  rabbitmq:
    appointments-exchange: mediqueue.appointments.exchange
    appointment-created-queue: mediqueue.appointments.created
    appointment-cancelled-queue: mediqueue.appointments.cancelled
    appointment-created-routing-key: appointments.created
    appointment-cancelled-routing-key: appointments.cancelled
    payments-exchange: mediqueue.payments.exchange
    payment-success-queue: mediqueue.payments.success
    payment-failed-queue: mediqueue.payments.failed
    payment-success-routing-key: payments.success
    payment-failed-routing-key: payments.failed

logging:
  level:
    com.mediqueue.notificacion: INFO

